services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_original_app 
    ports:
      - "8082:80" 
    volumes:
      - ./src:/var/www/html
      - ./Docker/Apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_original_db 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "13306:3306" 
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: laravel_original_adminer 
    restart: always
    ports:
      - "8882:8080"

volumes:
  db-data: